remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Raquel Neriz
logo: /assets/img/rn_logo.png
description: Sitio web profesional de Raquel Neriz
theme: jekyll-theme-minimal
