# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Raquel Neriz
email: info@raquelneriz.com
description: >- # this means to ignore newlines until "baseurl:"
  Sitio web profesional de Raquel Neriz.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://raquelneriz.com" # the base hostname & protocol for your site
instagram_username: raquel.neriz
github_username: jmamorteg

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# GitHub Pages configuration
repository: jmamorteg/raquelneriz.com
remote_theme: pages-themes/minimal@v0.2.0

# Navigation
header_pages:
  - about.markdown
  - blog.markdown
  - contact.markdown

# SEO settings
author: jmamorteg
  name: Raquel Neriz
  email: info@raquelneriz.com

# Social media
social:
  name: Raquel Neriz
  links:
    - https://github.com/jmamorteg

# Google Analytics (opcional)
# google_analytics: GA_TRACKING_ID

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - PLANTILLA-POST.md
  - start-server.bat
  - preview.html
