# Site settings
title: Raquel Neriz
email: info@raquelneriz.com
description: >- # this means to ignore newlines until "baseurl:"
  Sitio web profesional de Raquel Neriz.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jmamorteg.github.io/raquelneriz.com" # the base hostname & protocol for your site
instagram_username: raquel.neriz
github_username: jmamorteg

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages configuration
repository: jmamorteg/raquelneriz.com
remote_theme: pages-themes/minimal

# Theme-specific settings
logo: /assets/img/logo.png
show_downloads: false

# SEO settings
author: 
  name: Raquel Neriz
  
# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - TROUBLESHOOTING.md
